### PR TITLE
use settings when searching recipes

### PR DESCRIPTION
**Pull request by LordSir101**
Print out the url to confirm the request is using the settings

### CODE REVIEW

**Review by graemsheppard — COMMENTED** [review]
Why name the root application after one service?

**Comment by LordSir101** [comment]
> Why name the root application after one service?

Ok, idk exactly how to to this properly, but I need some kind of context for the db handler.  One of the suggested ways was to make the class extend Application and add it to the manifest.  I don't know if this is exactly what they meant but it seems to work.  If you know a better way to do this though I can change it.

**Comment by LordSir101** [comment]
> Why name the root application after one service?

Actually, a better way might be to just pass context from Browse fragment into getRecipeBackground()  I'll see if that works

**Comment by graemsheppard** [comment]
> > Why name the root application after one service?
> 
> Ok, idk exactly how to to this properly, but I need some kind of context for the db handler. One of the suggested ways was to make the class extend Application and add it to the manifest. I don't know if this is exactly what they meant but it seems to work. If you know a better way to do this though I can change it.

Ah alright I forgot about the context, idk how you would deal with that.

**Review by graemsheppard — APPROVED** [review]

**Pull request merged**
